defmodule Ithibati.Config do
  @moduledoc """
  Reads and validates the application's Ithibati configuration.

  `:users_key_type` and `:table_prefix` are read at compile time because they define schema fields
  and table names. Configure them before compiling Ithibati. The account schema, invitation
  schema and repo are read at runtime, when the consuming application's modules are available.

  `Ithibati.Identity.Sessions` reads and validates `:session_validity`.
  `initial_claim: :operator_code` protects `Ithibati.Identity.Instance.claim/2`. The relying-party
  ID and origin are per-call ceremony parameters, not Ithibati configuration.

  [Configuration and schemas](configuration.md) lists the keys, defaults and migration requirements.
  """

  # `table_prefix` names part of a table name; Ecto's `prefix` separately names a database schema.
  alias Ithibati.Schema.Invitation
  alias Ithibati.Schema.User

  @table_prefix Application.compile_env(:ithibati, :table_prefix, "ithibati")

  # Account foreign keys use the consumer's key type. Ithibati's own primary keys remain UUIDs.
  @users_key_type Application.compile_env(:ithibati, :users_key_type, :binary_id)

  # Validate before schemas consume the type so unsupported values fail at compilation.
  @users_key_type in [:binary_id, :id] ||
    raise(
      ArgumentError,
      "config :ithibati, users_key_type: must be :binary_id or :id, got: #{inspect(@users_key_type)}"
    )

  @doc "Returns `:open` or `:operator_code` for the first account claim."
  def initial_claim_mode do
    case Application.get_env(:ithibati, :initial_claim, :open) do
      mode when mode in [:open, :operator_code] ->
        mode

      other ->
        raise ArgumentError,
              "config :ithibati, initial_claim: must be :open or :operator_code, got: #{inspect(other)}"
    end
  end

  @doc "Returns the compiled table-name prefix (default: `ithibati`)."
  def table_prefix, do: @table_prefix

  @doc """
  Returns an Ithibati table name with the compiled prefix.

  For example, `table("keys")` returns `"ithibati_keys"` under the default configuration.
  This prefix is part of the table name, not a PostgreSQL schema name.
  """
  def table(suffix) when is_binary(suffix), do: "#{@table_prefix}_#{suffix}"

  @doc "Returns the compiled account foreign-key type: `:id` or `:binary_id` (default)."
  def users_key_type, do: @users_key_type

  @doc """
  Returns the configured account schema module.

  Raises `ArgumentError` when `:user_schema` is missing or the module does not export the
  integration generated by `Ithibati.Schema.User`. This validates the schema module, not its
  underlying table.
  """
  def user_schema do
    schema =
      Application.get_env(:ithibati, :user_schema) ||
        raise(
          ArgumentError,
          "config :ithibati, user_schema: MyApp.Accounts.User — the module that uses " <>
            "Ithibati.Schema.User. This library is told which schema is yours; it does not guess."
        )

    # Report the configuration error before a caller reaches an undefined schema marker.
    User.account_schema?(schema) ||
      raise(
        ArgumentError,
        "config :ithibati, user_schema: #{inspect(schema)} — that module does not " <>
          "`use Ithibati.Schema.User`"
      )

    schema
  end

  @doc """
  Returns the configured invitation schema module, or `nil` when none is configured.

  Raises `ArgumentError` if the module lacks the `Ithibati.Schema.Invitation` integration or
  its identifier field differs from the configured account schema's identifier.
  """
  def invitation_schema do
    case Application.get_env(:ithibati, :invitation_schema) do
      nil -> nil
      schema -> checked_invitation!(schema)
    end
  end

  @doc """
  Returns the configured invitation schema or raises `ArgumentError` when it is absent.

  Performs the same schema and identifier checks as `invitation_schema/0`. Use the non-bang
  variant when the absence of invitations is an expected configuration.
  """
  def invitation_schema! do
    invitation_schema() ||
      raise(
        ArgumentError,
        "config :ithibati, invitation_schema: MyApp.Accounts.Invitation — this library is told " <>
          "which schema holds your invitations before it can look one up."
      )
  end

  defp checked_invitation!(schema) do
    Invitation.invitation_schema?(schema) ||
      raise(
        ArgumentError,
        "config :ithibati, invitation_schema: #{inspect(schema)} — that module does not " <>
          "`use Ithibati.Schema.Invitation`"
      )

    invitee = schema.__ithibati_invitation__(:identifier)
    accounts = user_schema()
    account = accounts.__ithibati__(:identifier)

    invitee == account ||
      raise(
        ArgumentError,
        "#{inspect(schema)} invites by #{inspect(invitee)} and #{inspect(accounts)} is " <>
          "identified by #{inspect(account)} — an invitation has to be addressed to the thing an " <>
          "account is known by, or accepting one cannot fill it in."
      )

    schema
  end

  @doc """
  Returns the configured Ecto repo module.

  Raises `ArgumentError` when `:repo` is missing or the module does not export Ecto's adapter
  marker. This check does not start the repo or establish database connectivity;
  `Ithibati.Doctor.examine/1` checks whether it responds.
  """
  def repo do
    repo =
      Application.get_env(:ithibati, :repo) ||
        raise(
          ArgumentError,
          "config :ithibati, repo: MyApp.Repo — the repo this library reads and writes through. " <>
            "This library is told which repo is yours; it does not guess."
        )

    # Report an invalid repo setting before the first query dispatch.
    ecto_repo?(repo) ||
      raise(
        ArgumentError,
        "config :ithibati, repo: #{inspect(repo)} — that module is not an Ecto repo"
      )

    repo
  end

  defp ecto_repo?(module),
    do: Code.ensure_loaded?(module) and function_exported?(module, :__adapter__, 0)

  @doc """
  Returns an account struct if it belongs to the configured account schema.

  Raises `ArgumentError` for another struct or any non-struct value. This prevents an unrelated
  schema's ID from being treated as an account ID. It does not query the database or verify that
  the account row still exists.
  """
  def account!(account)

  def account!(%schema{} = account) do
    configured = user_schema()

    schema == configured || refuse(account)

    account
  end

  # A step may return `{:ok, nil}`; report it as an invalid account rather than a clause error.
  def account!(other), do: refuse(other)

  # Report the struct module without leaking its account fields into exception messages.
  defp refuse(%module{}), do: refuse_with("a #{inspect(module)}")
  defp refuse(other), do: refuse_with(inspect(other))

  defp refuse_with(description) do
    raise ArgumentError, "Ithibati: expected a #{inspect(user_schema())}, got #{description}"
  end
end
